### PR TITLE
Add Python 3.8 support and Django 2.1 to 3.0 testing

### PR DESCRIPTION
**Pull request by qbey**

### CODE REVIEW

**Review by xavfernandez — APPROVED** [review]

**Comment by xavfernandez** [comment]
Any chance to have this merged ? `django-nece` is currently crashing on Python 3.8 / Django 3.0 without this:
```
../../../venv/0/lib/python3.8/site-packages/nece/managers.py:82: in filter
    for key, value in kwargs.items():
RuntimeError: dictionary keys changed during iteration
```

**Comment by qbey** [comment]
> Any chance to have this merged ? `django-nece` is currently crashing on Python 3.8 / Django 3.0 without this:
> 
> ```
> ../../../venv/0/lib/python3.8/site-packages/nece/managers.py:82: in filter
>     for key, value in kwargs.items():
> RuntimeError: dictionary keys changed during iteration
> ```

Maybe @kemar or @metamatik may give us some help on this?  :wave: :pray: :heart:

**Comment by kemar** [comment]
Sup guyz!!! Sorry I don't have ownership to this repo :'(

**Comment by metamatik** [comment]
Hey 👋🏻 

Same here, I only contributed a very small patch 4 years ago, but I have no merge rights over here, and no sustained relationship with @tatterdemalion or anybody else who might, sorry 😅

**Comment by qbey** [comment]
Thank you for the answers! :smile:

**Comment by tatterdemalion** [comment]
It is me. I am not able to maintain this one anymore due to some changes in my life. I will write a notice on the README. Sorry everybody, I should have done this long before. 

I am merging this PR anyway. Please fork and continue on your own repo for future developments. Or, if anyone is interested I am willing to transfer the ownership of this one as well as the pip credentials (I am not sure if it is possible, and if I still have the access).

**Comment by k0t3n** [comment]
@tatterdemalion I have a need and desire to maintain this repository. Please contact me via [Telegram](t.me/k0t3n) or [email](mailto:k0t3n.mail@gmail.com)

**Comment by xavfernandez** [comment]
FWIW we forked the repository at https://github.com/Polyconseil/django-nece/ and plan to keep maintaining it in the coming years.
Since we could not get the PyPI project transferred we published it under: https://pypi.org/project/django-nece/ (vs https://pypi.org/project/nece/ previously).

**Pull request merged**
